"""
This is a setup.py script generated by py2applet with:

py2applet --make-setup --iconfile=icon.png  --emulate_shell_environment  --includes='xml.etree,xml.etree.ElementTree,uvicorn.protocols.http.auto'  --packages='falcon,uvicorn' --resources=../../driver/config.toml ../../driver/*.py

Usage:
    python setup.py py2app
"""

from setuptools import setup

# Edited to change the entry point
APP = ['../../driver/main.py']
DATA_FILES = ['../../driver/config.py',
 '../../driver/discovery.py',
 '../../driver/exceptions.py',
 '../../driver/log.py',
 '../../driver/main.py',
 '../../driver/management.py',
 '../../driver/polaris.py',
 '../../driver/setup.py',
 '../../driver/shr.py',
 '../../driver/stellarium.py',
 '../../driver/telescope.py',
 '../../driver/ui.py']
PLIST = {'CFBundleName': 'Alpaca Benro Polaris'}
OPTIONS = {'emulate_shell_environment': True,
  'iconfile': 'icon.png',
  'includes': 'xml.etree,xml.etree.ElementTree,uvicorn.protocols.http.auto',
  'packages': 'falcon,uvicorn',
  'resources': '../../driver/config.toml',
  'plist': PLIST}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
