# SPDX-License-Identifier: GPL-3.0-or-later
# Galactic_5_Cleanup.py
# Version: 5.1.0
# Part of the Galactic pipeline for panoramic astrophotography automation.
#
# ==============================================================================
# OVERVIEW
# ==============================================================================
# Removes intermediate/regenerable output from the Siril home directory tree,
# so a project can be reset to just its raw inputs (lights/darks/biases/flats)
# without hand-deleting everything scattered across every filter directory.
#
# Five targets, each independently switchable below:
#
#   1. */stacked/*     -- every <filter>/stacked directory (e.g. L/stacked,
#                          Ha/stacked, ...), the Galactic_1_Stack.py output.
#                          One level deep only -- a directory literally named
#                          "stacked" sitting directly under a filter directory.
#   2. **/process/*    -- every directory named "process" anywhere in the
#                          tree, at any depth -- <filter>/process (from
#                          Galactic_0_Calibration.py) as well as
#                          calibration/<filter>/flats/process,
#                          calibration/X/darks/process and
#                          calibration/X/biases/process.
#   3. *.bak           -- every .bak file anywhere in the tree (searched
#                          recursively, not just top-level -- a stray .bak
#                          can turn up at any depth).
#   4. star_removal/   -- the single top-level star_removal/ directory (see
#                          STAR_WORKING_DIR in Galactic_3_Stretch.py) holding
#                          stars_*.fits / stars_none_*.fits from StarXTerminator.
#   5. VeraLux_*       -- every file starting with "VeraLux_" anywhere in the
#                          tree (searched recursively), e.g. output left
#                          behind by a manual VeraLux StarComposer GUI session.
#
# All five are safe to remove: they hold nothing that isn't cheaply
# regenerated by re-running Galactic_0_Calibration.py / Galactic_1_Stack.py /
# Galactic_3_Stretch.py from the original lights/darks/biases/flats.
#
# DRY_RUN defaults to True -- the script only lists what it would delete.
# Set it to False once you've checked the list and are ready to actually
# delete.
#
# Usage
# -----
#   Run from Scripts menu with DRY_RUN = True first to review, then set
#   DRY_RUN = False and run again to actually delete.

import sirilpy as s
import shutil
import traceback
from pathlib import Path

# ==============================================================================
# CONFIGURATION
# ==============================================================================

# Master safety switch. True (default): only log what would be removed.
# False: actually delete.
DRY_RUN = True

# Independently switchable targets -- see OVERVIEW above.
REMOVE_STACKED_DIRS     = True    # */stacked
REMOVE_PROCESS_DIRS     = True    # **/process
REMOVE_BAK_FILES        = True    # **/*.bak
REMOVE_STAR_REMOVAL_DIR = True    # star_removal
REMOVE_VERALUX_FILES    = True    # **/VeraLux_*
# ==============================================================================


def siril_log(siril, msg):
    safe = msg.encode("ascii", errors="replace").decode("ascii")
    if not safe.strip():
        safe = " "
    siril.log(safe)


def _quote_if_needed(arg):
    """
    Wrap an argument in double quotes if it contains whitespace, so Siril's
    command-line parser treats it as a single token instead of splitting on
    the internal space (e.g. Windows paths like 'D:\\...\\HIP 97434\\...').
    See the identical helper in the other Galactic_*.py scripts for details.
    """
    txt = str(arg)
    if " " not in txt and "\t" not in txt:
        return txt
    if txt.startswith('"') and txt.endswith('"'):
        return txt
    return '"' + txt + '"'


def _dir_stats(path):
    """Return (n_files, total_bytes) for everything under path."""
    n_files = 0
    total_bytes = 0
    for p in path.rglob("*"):
        if p.is_file():
            n_files += 1
            try:
                total_bytes += p.stat().st_size
            except OSError:
                pass
    return n_files, total_bytes


def _human_size(n_bytes):
    size = float(n_bytes)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024.0:
            return "{:.1f}{}".format(size, unit)
        size /= 1024.0
    return "{:.1f}TB".format(size)


def remove_dirs(siril, home_dir, pattern, label):
    """
    Find every directory matching pattern under home_dir and remove it
    (dir and all its contents) unless DRY_RUN is set. Returns
    (n_dirs, n_files, total_bytes) for what was found/removed.
    """
    dirs = sorted(p for p in home_dir.glob(pattern) if p.is_dir())
    n_files_total = 0
    bytes_total = 0

    if not dirs:
        siril_log(siril, "  No " + label + " directories found.")
        return 0, 0, 0

    for d in dirs:
        n_files, n_bytes = _dir_stats(d)
        n_files_total += n_files
        bytes_total += n_bytes
        rel = d.relative_to(home_dir)
        if DRY_RUN:
            siril_log(siril, "  [DRY RUN] Would remove: " + str(rel)
                      + "  (" + str(n_files) + " file(s), "
                      + _human_size(n_bytes) + ")")
        else:
            try:
                shutil.rmtree(d)
                siril_log(siril, "  Removed: " + str(rel)
                          + "  (" + str(n_files) + " file(s), "
                          + _human_size(n_bytes) + ")")
            except OSError as exc:
                siril_log(siril, "  [WARNING] Could not remove " + str(rel)
                          + ": " + str(exc))

    return len(dirs), n_files_total, bytes_total


def remove_files(siril, home_dir, pattern, label):
    """
    Find every file matching pattern anywhere under home_dir (recursive)
    and remove it unless DRY_RUN is set. Returns (n_files, total_bytes).
    """
    files = sorted(p for p in home_dir.rglob(pattern) if p.is_file())
    bytes_total = 0

    if not files:
        siril_log(siril, "  No " + label + " files found.")
        return 0, 0

    for f in files:
        try:
            n_bytes = f.stat().st_size
        except OSError:
            n_bytes = 0
        bytes_total += n_bytes
        rel = f.relative_to(home_dir)
        if DRY_RUN:
            siril_log(siril, "  [DRY RUN] Would remove: " + str(rel)
                      + "  (" + _human_size(n_bytes) + ")")
        else:
            try:
                f.unlink()
                siril_log(siril, "  Removed: " + str(rel)
                          + "  (" + _human_size(n_bytes) + ")")
            except OSError as exc:
                siril_log(siril, "  [WARNING] Could not remove " + str(rel)
                          + ": " + str(exc))

    return len(files), bytes_total


def main():
    siril = s.SirilInterface()

    try:
        siril.connect()
        siril_log(siril, "Galactic_5_Cleanup v5.1.0 connected.")
    except Exception as exc:
        print("Galactic_5_Cleanup: could not connect: " + str(exc))
        return

    try:
        siril.cmd("requires", "1.4.0")
    except Exception:
        siril.error_messagebox("Galactic_5_Cleanup requires Siril 1.4.0 or later.")
        siril.disconnect()
        return

    try:
        home_dir = Path(siril.get_siril_wd())
        siril_log(siril, "Home directory: " + str(home_dir))
        siril_log(siril, "DRY_RUN: " + str(DRY_RUN)
                  + ("  (nothing will be deleted -- review the list below,"
                     " then set DRY_RUN = False to actually delete)"
                     if DRY_RUN else "  (files/directories WILL be deleted)"))

        total_dirs = total_files = total_bytes = 0

        siril_log(siril, " ")
        siril_log(siril, "=" * 60)
        siril_log(siril, "1. */stacked  (Galactic_1_Stack.py output)")
        siril_log(siril, "=" * 60)
        if REMOVE_STACKED_DIRS:
            n_dirs, n_files, n_bytes = remove_dirs(siril, home_dir, "*/stacked", "stacked")
            total_dirs += n_dirs; total_files += n_files; total_bytes += n_bytes
        else:
            siril_log(siril, "  Skipped (REMOVE_STACKED_DIRS = False).")

        siril_log(siril, " ")
        siril_log(siril, "=" * 60)
        siril_log(siril, "2. **/process  (Galactic_0_Calibration.py intermediates)")
        siril_log(siril, "=" * 60)
        if REMOVE_PROCESS_DIRS:
            n_dirs, n_files, n_bytes = remove_dirs(siril, home_dir, "**/process", "process")
            total_dirs += n_dirs; total_files += n_files; total_bytes += n_bytes
        else:
            siril_log(siril, "  Skipped (REMOVE_PROCESS_DIRS = False).")

        siril_log(siril, " ")
        siril_log(siril, "=" * 60)
        siril_log(siril, "3. *.bak  (backup files, anywhere in the tree)")
        siril_log(siril, "=" * 60)
        if REMOVE_BAK_FILES:
            n_files, n_bytes = remove_files(siril, home_dir, "*.bak", ".bak")
            total_files += n_files; total_bytes += n_bytes
        else:
            siril_log(siril, "  Skipped (REMOVE_BAK_FILES = False).")

        siril_log(siril, " ")
        siril_log(siril, "=" * 60)
        siril_log(siril, "4. star_removal  (Galactic_3_Stretch.py StarXTerminator working dir)")
        siril_log(siril, "=" * 60)
        if REMOVE_STAR_REMOVAL_DIR:
            n_dirs, n_files, n_bytes = remove_dirs(siril, home_dir, "star_removal", "star_removal")
            total_dirs += n_dirs; total_files += n_files; total_bytes += n_bytes
        else:
            siril_log(siril, "  Skipped (REMOVE_STAR_REMOVAL_DIR = False).")

        siril_log(siril, " ")
        siril_log(siril, "=" * 60)
        siril_log(siril, "5. VeraLux_*  (VeraLux StarComposer output, anywhere in the tree)")
        siril_log(siril, "=" * 60)
        if REMOVE_VERALUX_FILES:
            n_files, n_bytes = remove_files(siril, home_dir, "VeraLux_*", "VeraLux_*")
            total_files += n_files; total_bytes += n_bytes
        else:
            siril_log(siril, "  Skipped (REMOVE_VERALUX_FILES = False).")

        siril_log(siril, " ")
        siril_log(siril, "=" * 60)
        siril_log(siril, "Galactic_5_Cleanup complete.")
        siril_log(siril, "=" * 60)
        siril_log(siril, "  " + ("Would remove" if DRY_RUN else "Removed")
                  + ": " + str(total_dirs) + " director" + ("y" if total_dirs == 1 else "ies")
                  + ", " + str(total_files) + " file(s), "
                  + _human_size(total_bytes) + " total.")
        if DRY_RUN:
            siril_log(siril, "  This was a dry run -- set DRY_RUN = False and re-run to actually delete.")
        siril_log(siril, "=" * 60)

    except Exception as exc:
        siril_log(siril, "Unhandled error: " + str(exc))
        traceback.print_exc()

    finally:
        try:
            home_dir = Path(siril.get_siril_wd())
            siril.cmd("cd", _quote_if_needed(str(home_dir)))
        except Exception:
            pass
        siril.disconnect()


main()
