# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# app_api.py - Alpaca REST API Application module
# -----------------------------------------------------------------------------
# MIT License
#
# Copyright (c) 2025 David Morrison
# -----------------------------------------------------------------------------

import inspect
import uvicorn
from falcon import App, asgi, HTTP_200, HTTPFound
import asyncio
import management
from config import Config
from shr import LifecycleController, LifecycleEvent, check_port_bindable, describe_bind_error
from app_web import ensure_tls_cert, TLS_CERT_PATH, TLS_KEY_PATH

#########################
# FOR EACH ASCOM DEVICE #
#########################
import telescope
import rotator

#--------------
API_VERSION = 1           
#--------------

def init_routes(app: App, devname: str, module):
    memlist = inspect.getmembers(module, inspect.isclass)
    for cname,ctype in memlist:
        if ctype.__module__ == module.__name__:
            app.add_route(f'/api/v{API_VERSION}/{devname}/{{devnum:int(min=0)}}/{cname.lower()}', ctype())


class RedirectResource:
    async def on_get(self, req, resp):
        https = Config.enable_https
        proto = 'https' if https else 'http'
        port  = Config.alpaca_pilot_https_port if https else Config.alpaca_pilot_http_port
        host  = req.host.split(':')[0]
        port_suffix = '' if (https and port == 443) or (not https and port == 80) else f':{port}'
        raise HTTPFound(f'{proto}://{host}{port_suffix}/?api={Config.alpaca_restapi_port}&host={host}')


async def alpaca_rest_httpd(logger, lifecycle: LifecycleController):
    if not Config.enable_restapi:
        logger.info("==STARTUP== Alpaca REST API disabled by config, not starting.")
        return        
    rest_app = asgi.App(middleware=[CORSMiddleware()])

    init_routes(rest_app, 'telescope', telescope)
    init_routes(rest_app, 'rotator', rotator)

    rest_app.add_route('/management/apiversions', management.apiversions())
    rest_app.add_route(f'/management/v{API_VERSION}/description', management.description())
    rest_app.add_route(f'/management/v{API_VERSION}/configureddevices', management.configureddevices())
    if Config.enable_pilot:
        rest_app.add_route('/setup', RedirectResource())
        rest_app.add_route(f'/setup/v{API_VERSION}/telescope/0/setup', RedirectResource())
        rest_app.add_route(f'/setup/v{API_VERSION}/rotator/0/setup', RedirectResource())

    # Ensure TLS cert exists (will reuse the one generated by app_web)
    tls_ok = Config.enable_rest_https and ensure_tls_cert(Config.alpaca_restapi_ip_address, logger)

    alpaca_server = None
    try:
        bind_err = check_port_bindable(Config.alpaca_restapi_ip_address, Config.alpaca_restapi_port)
        if bind_err is not None:
            logger.error("==STARTUP FAILED== " + describe_bind_error(
                bind_err, Config.alpaca_restapi_ip_address, Config.alpaca_restapi_port, "Alpaca REST API"))
            await lifecycle.signal(LifecycleEvent.SHUTDOWN)
            return

        ssl_kwargs = dict(
            ssl_certfile=str(TLS_CERT_PATH),
            ssl_keyfile=str(TLS_KEY_PATH),
        ) if tls_ok else {}

        alpaca_config = uvicorn.Config(
            rest_app,
            host=Config.alpaca_restapi_ip_address,
            port=Config.alpaca_restapi_port,
            log_level="error",
            log_config=None,               # keep uvicorn's log records on our own logging pipeline/formatting instead of its separate stderr handler
            timeout_graceful_shutdown=3,   # bound connection-drain wait; default is None (waits forever for open connections)
            **ssl_kwargs,
        )
        alpaca_server = uvicorn.Server(alpaca_config)
        proto = 'HTTPS' if tls_ok else 'HTTP'
        logger.info(f'==STARTUP== Serving ASCOM Alpaca REST API ({proto}) on '
                    f'{Config.alpaca_restapi_ip_address}:{Config.alpaca_restapi_port}.')

        await asyncio.gather(
            lifecycle._wrap(alpaca_server.serve()),
            lifecycle.wait_for_event()
        )
    except asyncio.CancelledError:
        logger.info("==CANCELLED== Alpaca REST API cancel received.")
    except Exception as e:
        logger.exception(f"==EXCEPTION== Alpaca REST API unhandled exception: {e}")
    finally:
        logger.info("==SHUTDOWN== Alpaca REST API shutting down.")
        if alpaca_server and alpaca_server.started:
            await alpaca_server.shutdown()


class CORSMiddleware:
    async def process_request(self, req, resp):
        pass

    async def process_response(self, req, resp, resource, req_succeeded):
        origin = req.headers.get("origin", "*")
        resp.set_header("Access-Control-Allow-Origin", origin)
        resp.set_header("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS")
        resp.set_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        resp.set_header("Access-Control-Allow-Credentials", "true")

        if req.method == "OPTIONS":
            resp.status = HTTP_200
            resp.complete = True